import { Product } from "./type";

export const products : Product[]=[

    
    {
        id : 1,
        title : "Nike Air Max Pulse",
        slug : "Nike-Air-Max-Pulse-2",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "mens",
        img : ["/assets/Itemssss (1).png"],
        isBestSelling : true,
    },
    
    {
        id : 2,
        title : "Nike Air Max Pulse-2",
        slug : "Danish-abbasiiiii",
        price : 16000,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "mens",
        img :  ["/assets/Itemssss (2).png"],
        isBestSelling : true,
    },
    
    {
        id : 3,
        title : "Nike Air Max Pulse-3",
        slug : "Danish-abbasiii-2",
        price : 23500,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "mens",
        img :["/assets/Itemssss (3).png"],
        isBestSelling : true,
    },
    {
        id : 4,
        title : "Nike Air Max Pulse",
        slug : "Nike-Air-Max-Pulse-3",
        price : 13995,
        discount :25,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "womens",
        img : ["/assets/Itemssss (1).png"],
        isBestSelling : true,
    },
    
    {
        id : 5,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiiiii-4",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "womens",
        img :  ["/assets/Itemssss (2).png"],
        isBestSelling : true,
    },
    
    {
        id : 6,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiii-5",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "womens",
        img :["/assets/Itemssss (3).png"],
        isBestSelling : true,
    },
    {
        id : 7,
        title : "Nike Air Max Pulse",
        slug : "Nike-Air-Max-Pulse-6",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "kids",
        img : ["/assets/Itemssss (1).png"],
    },
    
    {
        id : 8,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiiiii-7",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "kids",
        img :  ["/assets/Itemssss (2).png"],
        
    },
    
    {
        id : 9,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiii-8",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "kids",
        img :["/assets/Itemssss (3).png"],
        
    },
    
    {
        id : 10,
        title : "Nike Air Max Pulse",
        slug : "Nike-Air-Max-Pulse-9",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "sale",
        img : ["/assets/Itemssss (1).png"],
       
    },
    
    {
        id : 11,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiiiii-10",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "sale",
        img :  ["/assets/Itemssss (2).png"]
    },
    
    {
        id : 12,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiii-11",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "sale",
        img :["/assets/Itemssss (3).png"]
    },
    {
        id : 13,
        title : "Nike Air Max Pulse",
        slug : "Nike-Air-Max-Pulse-10",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "SNKRS",
        img : ["/assets/Itemssss (1).png"],
    },
    
    {
        id : 14,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiiiii-13",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "SNKRS",
        img :  ["/assets/Itemssss (2).png"]
    },
    
    {
        id : 15,
        title : "Nike Air Max Pulse",
        slug : "Danish-abbasiii-14",
        price : 13995,
        discount :0,
        description : "lloreeeememememememememememememememm",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "SNKRS",
        img :["/assets/Itemssss (3).png"]
    },
    {
        id : 16,
        title : "Nike Dri-FIT ADV TechKnit Ultra",
        slug : "gearup1",
        price : 3895,
        discount :0,
        description : "Men's Short-Sleeve Running Top",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "mens",
        img : ["/assets/g1.png"],
        isBestSelling : true,
        isGearUp : true
    },
    {
        id : 17,
        title : "Nike Dri-FIT Challenger",
        slug : "gearup2",
        price : 2495,
        discount :0,
        description : "Men's Short-Sleeve Running Top",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "mens",
        img : ["/assets/g2.png"],
        isBestSelling : true,
        isGearUp : true
    },
    {
        id : 18,
        title : "Nike Dri-FIT ADV Run Division",
        slug : "gearup3",
        price : 5295,
        discount :0,
        description : "Women's Long-Sleeve Running Top",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "womens",
        img : ["/assets/g3.png"],
        isBestSelling : true,
        isGearUp : true
    },
    {
        id : 19,
        title : "Nike Fast",
        slug : "gearup3",
        price : 3795,
        discount :0,
        description : " Mid-Rise 7/8 Running Leggings",
        size: ["S","M","L","XL"],
        color: ["#ffffff","#000000","#e60000"],
        qty:1,
        category : "womens",
        img : ["/assets/g4.png"],
        isBestSelling : true,
        isGearUp : true
    },
    
]